graph_theory/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from extended_user.views import SignUp, ProfileDetailView
from graph_theory import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/course/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('extended_user.urls')),
    path('reg/', SignUp.as_view(), name='reg'),
    path('course/', include('course.urls')),
    path('builder/', include('builder.urls')),
    path('sets/', include('sets.urls')),
    path('martor/', include('martor.urls')),
    path("select2/", include("django_select2.urls")),
    path('accounts/profile/', ProfileDetailView.as_view(), name='self-profile-detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sets/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    path('calculate/', CalcView.as_view(), name='calculate'),
    path(r'', TemplateView.as_view(template_name='sets/main.html'), name='sets-main'),
]

course/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import SET_NULL, CASCADE
from django.urls import reverse_lazy

from martor.models import MartorField

from builder.models import Graph
from extended_user.models import Profile


class BaseUnit:
    pass


class Course(BaseUnit, models.Model):
    name = models.CharField(max_length=1024, null=True, verbose_name='Название')
    creator = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='courses_by_creator',
                                verbose_name='Автор')
    last_editor = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='courses_by_last_editor',
                                    verbose_name='Последний редактор')
    time_create = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Время создания')
    time_edit = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Последнее редактирование')
    description = models.TextField(max_length=4096, default="Описание не заполнено", verbose_name='Описание')
    editors = models.ManyToManyField(to=Profile, verbose_name='Редакторы')
    private = models.BooleanField(default=False, verbose_name='С ограниченным доступом')
    password = models.CharField(max_length=1024, blank=True, null=True, verbose_name='Пароль')

    def __str__(self):
        return self.name or "Нет названия"

    def get_absolute_url(self):
        return reverse_lazy('course-detail', kwargs={'pk': self.pk})

    def is_parent_creator(self, user_pk):
        raise NotImplementedError


class Lesson(BaseUnit, models.Model):
    name = models.CharField(max_length=1024, null=True, verbose_name='Название')
    creator = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='lessons_by_creator',
                                verbose_name='Автор')
    last_editor = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='lessons_by_last_editor',
                                    verbose_name='Последний редактор')
    time_create = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Время создания')
    time_edit = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Последнее редактирование')
    description = models.TextField(max_length=4096, default="Описание не заполнено", verbose_name='Описание')
    course = models.ForeignKey(to=Course, on_delete=CASCADE, related_name='lessons', verbose_name='Курс')

    def __str__(self):
        return self.name or "Нет названия"

    def get_absolute_url(self):
        return reverse_lazy('lesson-detail', kwargs={'pk': self.pk})

    def is_parent_creator(self, user_pk):
        return self.creator_id == user_pk

    @property
    def parent(self):
        return self.course

    @classmethod
    def parent_class(cls):
        return Course


class Step(BaseUnit, models.Model):  # шаги занятия
    name = models.CharField(max_length=1024, null=True, verbose_name='Название')
    creator = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='steps_by_creator',
                                verbose_name='Автор')
    last_editor = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='steps_by_last_editor',
                                    verbose_name='Последний редактор')
    time_create = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Время создания')
    time_edit = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Последнее редактирование')
    description = models.TextField(max_length=4096, default="Описание не заполнено", verbose_name='Описание')
    lesson = models.ForeignKey(to=Lesson, on_delete=CASCADE, related_name='steps', verbose_name='Занятие')
    data = MartorField(verbose_name='Материалы шага')
    graph = models.ForeignKey(to=Graph, null=True, blank=True, on_delete=SET_NULL, verbose_name='Иллюстрация к шагу')

    def __str__(self):
        return self.name or "Нет названия"

    def get_absolute_url(self):
        return reverse_lazy('step-detail', kwargs={'pk': self.pk})

    def is_parent_creator(self, user_pk):
        return self.creator_id == user_pk or self.parent.is_parent_creator(user_pk)

    @property
    def parent(self):
        return self.lesson

    @classmethod
    def parent_class(cls):
        return Lesson


class Task(BaseUnit, models.Model):  # в одном занятии может быть несколько заданий
    name = models.CharField(max_length=1024, null=True, verbose_name='Название')
    creator = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='tasks_by_creator',
                                verbose_name='Автор')
    last_editor = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='tasks_by_last_editor',
                                    verbose_name='Последний редактор')
    time_create = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Время создания')
    time_edit = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Последнее редактирование')
    description = models.TextField(max_length=4096, default="Описание не заполнено", verbose_name='Описание')
    step = models.ForeignKey(to=Step, on_delete=CASCADE, related_name='tasks', verbose_name='Шаг')
    max_mark = models.IntegerField(verbose_name='Максимальная оценка')
    weight = models.IntegerField(default=10, verbose_name='Вес оценки')
    auto_test = models.BooleanField(verbose_name="Автоматическая проверка", default=False)
    correct_answers = models.TextField(verbose_name="Правильные ответы (варианты через ;)", null=True, blank=True)
    graph = models.ForeignKey(to=Graph, null=True, blank=True, on_delete=SET_NULL, verbose_name='Иллюстрация к заданию')

    def __str__(self):
        return self.name or "Нет названия"

    def get_absolute_url(self):
        return reverse_lazy('task-detail', kwargs={'pk': self.pk})

    @property
    def answer_count(self):
        return self.homeworks.count()

    def is_parent_creator(self, user_pk):
        return self.creator_id == user_pk or self.parent.is_parent_creator(user_pk)

    @property
    def parent(self):
        return self.step

    @classmethod
    def parent_class(cls):
        return Step


class HomeWork(BaseUnit, models.Model):
    name = models.CharField(max_length=1024, null=True, verbose_name='Название', blank=True)
    creator = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='homeworks_by_creator',
                                verbose_name='Автор')
    last_editor = models.ForeignKey(to=Profile, on_delete=SET_NULL, null=True, related_name='homeworks_by_last_editor',
                                    verbose_name='Проверяющий')
    time_create = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Время создания')
    time_edit = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Последнее редактирование')
    description = models.TextField(max_length=1024, verbose_name='Решение', null=True)
    task = models.ForeignKey(to=Task, on_delete=SET_NULL, null=True, related_name='homeworks', verbose_name='Задание')
    mark = models.IntegerField(verbose_name='Оценка', null=True, blank=True)

    @property
    def title(self):
        if len(self.description) > 50:
            return self.description[:50] + '...'
        return self.description

    @property
    def title_with_author(self):
        return f"{self.title} ({self.creator})"

    def __str__(self):
        return self.title_with_author

    def get_absolute_url(self):
        return reverse_lazy('homework-detail', kwargs={'pk': self.pk})

    def is_parent_creator(self, user_pk):
        return self.creator_id == user_pk or self.parent.is_parent_creator(user_pk)

    @property
    def table_color(self):
        if self.mark == self.task.max_mark:
            return 'green'
        if self.mark is None:
            return ''
        if self.mark == 0:
            return 'red'
        return 'yellow'

    @property
    def parent(self):
        return self.task

    @classmethod
    def parent_class(cls):
        return Task


class RegOnCourse(models.Model):
    intern = models.ForeignKey("extended_user.Profile", verbose_name="Студент", on_delete=models.RESTRICT,
                               related_name="regs_by_student")
    course_id = models.ForeignKey("Course", verbose_name="Курс", on_delete=models.RESTRICT,
                                  related_name="regs_by_course")
    rating = models.IntegerField("Обратная связь", null=True, blank=True, validators=[MinValueValidator(0),
                                                                                      MaxValueValidator(5)])

course/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from course.models import Task, HomeWork
from course.tables import HomeWorkTable
from course.views.mixins import AddTitleFormMixin, DetailWithSingleTable, ProDetailView, SaveEditorMixin
from funcs import OnlyParentCreatorMixin


class TaskCreateView(OnlyParentCreatorMixin, LoginRequiredMixin, SaveEditorMixin, AddTitleFormMixin, CreateView):
    model = Task
    template_name = 'task/create.html'

    fields = ('name', 'step', 'description', 'graph', 'max_mark', 'weight', 'auto_test', 'correct_answers')
    title = "Добавление задания"

    def get_initial(self):
        initial_data = {}
        for i in self.fields:
            initial_data[i] = self.request.GET.get(i)
            initial_data['step'] = self.kwargs['from']
        return initial_data

    def get_success_url(self):
        return reverse_lazy('step-detail', kwargs={'pk': self.object.step.id})


class TaskDetailView(DetailWithSingleTable):
    model = Task
    template_name = 'task/detail.html'

    table_model = HomeWork
    table_class = HomeWorkTable

    def get_table_data(self):
        task = self.object.id
        task_obj = Task.objects.get(pk=task)
        if not self.request.user.is_authenticated:
            return self.table_model.objects.none()
        if self.request.user.profile == task_obj.creator or self.request.user.is_superuser:
            return self.table_model.objects.filter(task_id=task)
        else:
            return self.table_model.objects.filter(task_id=task, creator=self.request.user.profile)

    def get_table_kwargs(self):
        kwargs = {}
        if self.request.user.is_authenticated:
            if self.request.user.profile in (self.object.creator, self.object.last_editor) \
                    or self.request.user.is_superuser:
                kwargs['exclude'] = ('title', )
            else:
                kwargs['exclude'] = ('title_with_author', )
        return kwargs

templates/task/create.html
{% include "base.html" with page_title=title %}

{% load static %}
{% load martortags %}

{% block custom_css %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}


{% block container %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{{ title }}</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">
                        {% if editing %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_graph').select2();
        });
    </script>
    <script>
        let optionSelected = id_auto_test.checked;
        if (optionSelected === false) {
            $('#id_correct_answers').parent().hide();
          }
        else {
            $('#id_correct_answers').parent().show();
        }
        $('#id_auto_test').change(function () {
            let optionSelected = id_auto_test.checked;
            if (optionSelected === false) {
                $('#id_correct_answers').parent().hide();
              }
            else {
                $('#id_correct_answers').parent().show();
            }
    });
    </script>
{% endblock %}

templates/task/detail.html
{% include "base.html" with page_title=object.name %}

{% block container %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{{ object }}</h5>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-3">Создатель задания</dt>
                    <dd class="col-sm-9">
                        {% if object.creator_id %}
                            <a href="{% url 'profile-detail' pk=object.creator_id %}">{{ object.creator|default_if_none:"&#10060" }}</a>
                        {% else %}
                            {{ object.creator|default_if_none:"&#10060" }}
                        {% endif %}
                    </dd>
                    <dt class="col-sm-3">Описание</dt>
                    <dd class="col-sm-9">{{ object.description|default_if_none:"&#10060" }}</dd>
                    <dt class="col-sm-3">Максимальный балл</dt>
                    <dd class="col-sm-9">{{ object.max_mark|default_if_none:"&#10060" }}</dd>
                    <dt class="col-sm-3">Вес оценки</dt>
                    <dd class="col-sm-9">{{ object.weight|default_if_none:"&#10060" }}</dd>
                </dl>
                <a href="{% url 'step-detail' object.step.pk %}" class="btn btn-primary">К шагу</a>
                <a href="{% url 'homework-create' object.pk %}" class="btn btn-success">Добавить решение</a>
            </div>
        {% if object.graph %}
            {% include object.graph.get_absolute_file_upload_url %}
        {% endif %}
        {% load render_table from django_tables2 %}
        <h1>Решения</h1>
        {% render_table table %}
        </div>
    </div>

{% endblock %}